name = "bilipgc"
main = "src-worker/index.ts"
compatibility_date = "2023-05-27"
workers_dev = false

routes = [
  { pattern = "bilipgc.cfm.moe/*", zone_id = "0895789f7f10ff92afcd5410777da6bf" },
]

r2_buckets = [
  { binding = "R2", bucket_name = "bilipgc", preview_bucket_name = "bilipgc" }
]

[site]
bucket = "./dist"

[placement]
mode = "smart"
