// @generated by protobuf-ts 2.9.0 with parameter long_type_number
// @generated from protobuf file "bilibili.pgc.gateway.player.v2/PlayURL.proto" (package "bilibili.pgc.gateway.player.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PlayURL } from "./PlayURL";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PlayViewReply } from "./PlayURL";
import type { PlayViewReq } from "./PlayURL";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 视频url
 *
 * @generated from protobuf service bilibili.pgc.gateway.player.v2.PlayURL
 */
export interface IPlayURLClient {
    /**
     * 播放页信息
     *
     * @generated from protobuf rpc: PlayView(bilibili.pgc.gateway.player.v2.PlayViewReq) returns (bilibili.pgc.gateway.player.v2.PlayViewReply);
     */
    playView(input: PlayViewReq, options?: RpcOptions): UnaryCall<PlayViewReq, PlayViewReply>;
    /**
     * @generated from protobuf rpc: PlayViewComic(bilibili.pgc.gateway.player.v2.PlayViewReq) returns (bilibili.pgc.gateway.player.v2.PlayViewReply);
     */
    playViewComic(input: PlayViewReq, options?: RpcOptions): UnaryCall<PlayViewReq, PlayViewReply>;
}
/**
 * 视频url
 *
 * @generated from protobuf service bilibili.pgc.gateway.player.v2.PlayURL
 */
export class PlayURLClient implements IPlayURLClient, ServiceInfo {
    typeName = PlayURL.typeName;
    methods = PlayURL.methods;
    options = PlayURL.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 播放页信息
     *
     * @generated from protobuf rpc: PlayView(bilibili.pgc.gateway.player.v2.PlayViewReq) returns (bilibili.pgc.gateway.player.v2.PlayViewReply);
     */
    playView(input: PlayViewReq, options?: RpcOptions): UnaryCall<PlayViewReq, PlayViewReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PlayViewReq, PlayViewReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PlayViewComic(bilibili.pgc.gateway.player.v2.PlayViewReq) returns (bilibili.pgc.gateway.player.v2.PlayViewReply);
     */
    playViewComic(input: PlayViewReq, options?: RpcOptions): UnaryCall<PlayViewReq, PlayViewReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PlayViewReq, PlayViewReply>("unary", this._transport, method, opt, input);
    }
}
