// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "bilibili.community.service.dm.v1/DM.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DM } from "./DM";
import type { DmExpoReportRes } from "./DM";
import type { DmExpoReportReq } from "./DM";
import type { DmSegSDKReply } from "./DM";
import type { DmSegSDKReq } from "./DM";
import type { DmSegOttReply } from "./DM";
import type { DmSegOttReq } from "./DM";
import type { Response } from "./DM";
import type { DmPlayerConfigReq } from "./DM";
import type { DmViewReply } from "./DM";
import type { DmViewReq } from "./DM";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DmSegMobileReply } from "./DM";
import type { DmSegMobileReq } from "./DM";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 弹幕
 *
 * @generated from protobuf service bilibili.community.service.dm.v1.DM
 */
export interface IDMClient {
    /**
     * 获取分段弹幕
     *
     * @generated from protobuf rpc: DmSegMobile(bilibili.community.service.dm.v1.DmSegMobileReq) returns (bilibili.community.service.dm.v1.DmSegMobileReply);
     */
    dmSegMobile(input: DmSegMobileReq, options?: RpcOptions): UnaryCall<DmSegMobileReq, DmSegMobileReply>;
    /**
     * 客户端弹幕元数据 字幕、分段、防挡蒙版等
     *
     * @generated from protobuf rpc: DmView(bilibili.community.service.dm.v1.DmViewReq) returns (bilibili.community.service.dm.v1.DmViewReply);
     */
    dmView(input: DmViewReq, options?: RpcOptions): UnaryCall<DmViewReq, DmViewReply>;
    /**
     * 修改弹幕配置
     *
     * @generated from protobuf rpc: DmPlayerConfig(bilibili.community.service.dm.v1.DmPlayerConfigReq) returns (bilibili.community.service.dm.v1.Response);
     */
    dmPlayerConfig(input: DmPlayerConfigReq, options?: RpcOptions): UnaryCall<DmPlayerConfigReq, Response>;
    /**
     * ott弹幕列表
     *
     * @generated from protobuf rpc: DmSegOtt(bilibili.community.service.dm.v1.DmSegOttReq) returns (bilibili.community.service.dm.v1.DmSegOttReply);
     */
    dmSegOtt(input: DmSegOttReq, options?: RpcOptions): UnaryCall<DmSegOttReq, DmSegOttReply>;
    /**
     * SDK弹幕列表
     *
     * @generated from protobuf rpc: DmSegSDK(bilibili.community.service.dm.v1.DmSegSDKReq) returns (bilibili.community.service.dm.v1.DmSegSDKReply);
     */
    dmSegSDK(input: DmSegSDKReq, options?: RpcOptions): UnaryCall<DmSegSDKReq, DmSegSDKReply>;
    /**
     * @generated from protobuf rpc: DmExpoReport(bilibili.community.service.dm.v1.DmExpoReportReq) returns (bilibili.community.service.dm.v1.DmExpoReportRes);
     */
    dmExpoReport(input: DmExpoReportReq, options?: RpcOptions): UnaryCall<DmExpoReportReq, DmExpoReportRes>;
}
/**
 * 弹幕
 *
 * @generated from protobuf service bilibili.community.service.dm.v1.DM
 */
export class DMClient implements IDMClient, ServiceInfo {
    typeName = DM.typeName;
    methods = DM.methods;
    options = DM.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 获取分段弹幕
     *
     * @generated from protobuf rpc: DmSegMobile(bilibili.community.service.dm.v1.DmSegMobileReq) returns (bilibili.community.service.dm.v1.DmSegMobileReply);
     */
    dmSegMobile(input: DmSegMobileReq, options?: RpcOptions): UnaryCall<DmSegMobileReq, DmSegMobileReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DmSegMobileReq, DmSegMobileReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 客户端弹幕元数据 字幕、分段、防挡蒙版等
     *
     * @generated from protobuf rpc: DmView(bilibili.community.service.dm.v1.DmViewReq) returns (bilibili.community.service.dm.v1.DmViewReply);
     */
    dmView(input: DmViewReq, options?: RpcOptions): UnaryCall<DmViewReq, DmViewReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DmViewReq, DmViewReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 修改弹幕配置
     *
     * @generated from protobuf rpc: DmPlayerConfig(bilibili.community.service.dm.v1.DmPlayerConfigReq) returns (bilibili.community.service.dm.v1.Response);
     */
    dmPlayerConfig(input: DmPlayerConfigReq, options?: RpcOptions): UnaryCall<DmPlayerConfigReq, Response> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DmPlayerConfigReq, Response>("unary", this._transport, method, opt, input);
    }
    /**
     * ott弹幕列表
     *
     * @generated from protobuf rpc: DmSegOtt(bilibili.community.service.dm.v1.DmSegOttReq) returns (bilibili.community.service.dm.v1.DmSegOttReply);
     */
    dmSegOtt(input: DmSegOttReq, options?: RpcOptions): UnaryCall<DmSegOttReq, DmSegOttReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DmSegOttReq, DmSegOttReply>("unary", this._transport, method, opt, input);
    }
    /**
     * SDK弹幕列表
     *
     * @generated from protobuf rpc: DmSegSDK(bilibili.community.service.dm.v1.DmSegSDKReq) returns (bilibili.community.service.dm.v1.DmSegSDKReply);
     */
    dmSegSDK(input: DmSegSDKReq, options?: RpcOptions): UnaryCall<DmSegSDKReq, DmSegSDKReply> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DmSegSDKReq, DmSegSDKReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DmExpoReport(bilibili.community.service.dm.v1.DmExpoReportReq) returns (bilibili.community.service.dm.v1.DmExpoReportRes);
     */
    dmExpoReport(input: DmExpoReportReq, options?: RpcOptions): UnaryCall<DmExpoReportReq, DmExpoReportRes> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DmExpoReportReq, DmExpoReportRes>("unary", this._transport, method, opt, input);
    }
}
