// @generated by protobuf-ts 2.9.0 with parameter long_type_number
// @generated from protobuf file "bilibili.app.playerunite.v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Player } from "./playerunite";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PlayViewUniteReply } from "./playerunite";
import type { PlayViewUniteReq } from "./playerunite";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 统一视频url
 *
 * @generated from protobuf service bilibili.app.playerunite.v1.Player
 */
export interface IPlayerClient {
    /**
     * 视频地址
     *
     * @generated from protobuf rpc: PlayViewUnite(bilibili.app.playerunite.v1.PlayViewUniteReq) returns (bilibili.app.playerunite.v1.PlayViewUniteReply);
     */
    playViewUnite(input: PlayViewUniteReq, options?: RpcOptions): UnaryCall<PlayViewUniteReq, PlayViewUniteReply>;
}
/**
 * 统一视频url
 *
 * @generated from protobuf service bilibili.app.playerunite.v1.Player
 */
export class PlayerClient implements IPlayerClient, ServiceInfo {
    typeName = Player.typeName;
    methods = Player.methods;
    options = Player.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 视频地址
     *
     * @generated from protobuf rpc: PlayViewUnite(bilibili.app.playerunite.v1.PlayViewUniteReq) returns (bilibili.app.playerunite.v1.PlayViewUniteReply);
     */
    playViewUnite(input: PlayViewUniteReq, options?: RpcOptions): UnaryCall<PlayViewUniteReq, PlayViewUniteReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PlayViewUniteReq, PlayViewUniteReply>("unary", this._transport, method, opt, input);
    }
}
